name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.15.0
    secrets: inherit
    with:
      main-branch-name: main
      number-of-agents: 3
      pnpm-version: '10'
      init-commands: |
        npx playwright install --with-deps
      parallel-commands: |
        pnpm nx-cloud record -- pnpm nx format:check
      parallel-commands-on-agents: |
        pnpm nx affected --target=lint --parallel=3
        pnpm nx affected --target=test --parallel=3 --ci --code-coverage
        pnpm nx affected --target=build --parallel=3
        pnpm nx affected --target=e2e --parallel=3
